#!/bin/sh

set -e

if [ "$1" = "remove" ]; then
    if [ -x "/usr/bin/deb-systemd-helper" ]; then
        deb-systemd-helper mask spocon.service >/dev/null
    fi
fi

if [ "$1" = "purge" ]; then
    if [ -x "/usr/bin/deb-systemd-helper" ]; then
        deb-systemd-helper purge spocon.service >/dev/null
        deb-systemd-helper unmask spocon.service >/dev/null
    fi

    deluser --force spocon || true
    delgroup --force spocon >/dev/null 2>&1 || true
    rm -rf /opt/spocon
fi

if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
fi