#!/bin/sh

set -e

if test -f "/opt/spocon/config.toml"; then
    mv /opt/spocon/config.toml /opt/spocon/conf.usercustom
fi

if ! getent group spocon >/dev/null 2>&1; then
    addgroup --system spocon
fi

if ! id spocon >/dev/null 2>&1; then
    adduser --system --disabled-password --disabled-login --ingroup spocon spocon
fi