Document: spocon
Title: Debian spocon Manual
Author: Thorsten H
Abstract: This manual describes what spocon is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/spocon/spocon.sgml.gz

Format: postscript
Files: /usr/share/doc/spocon/spocon.ps.gz

Format: text
Files: /usr/share/doc/spocon/spocon.text.gz

Format: HTML
Index: /usr/share/doc/spocon/html/index.html
Files: /usr/share/doc/spocon/html/*.html
